# NumPy

 <img src="https://numpy.org/images/logos/numpy.svg" alt="NumPy" width="100px" /><br>

The fundamental package for scientific computing with Python. Use for basic data representation and linear algebra operation. NumPy also provide several data formats and array format for python. The data manipulation and data preprocessing also can be done with NumPy. From Aj.Ple experience, Aj.Ple suggest to change data representation to NumPy for Data Engineering & Data Analytics work. <br>

P.S. Linear Algebra is about linear equation in form of vector and matrix !!

www.numpy.org

### 1. NumPy Array

To use external Library in PyThon, we will use the command called <i>import</i>.<br> In this example, we use external library called <i>NumPy</i> and give it a short name as <i>np</i>. 

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[0]

1

In [4]:
a[2:5]

array([3, 4, 5])

In [5]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [6]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
a[-1]

10

In [8]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [9]:
a[-5:-1]

array([6, 7, 8, 9])

In [10]:
np.size(a)

10

In [11]:
np.shape(a)

(10,)

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a[0,0]

1

In [14]:
a[1,:]

array([4, 5, 6])

In [15]:
a[:,-1]

array([3, 6, 9])

In [16]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

4

In [18]:
np.size(a,1)

3

In [19]:
np.ndim(a)

2

### Data is Matrix.
So, Matrix management == Data Management <br>
rows    = samples <br>
columns = attributes, features

In [20]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [21]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

### 2. Special Type of Matrix

In [22]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [23]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [24]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [25]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [26]:
c*d

array([[8., 0.],
       [0., 8.]])

In [27]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [28]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [29]:

np.empty([5,5])

array([[ 4.64743498e-310,  8.15208316e-322, -3.40602994e-294,
         4.39324667e+228,  5.37988202e+228],
       [ 1.38795503e+219,  2.86749934e+161,  5.95144714e+228,
         1.99886516e+161,  1.09313427e+189],
       [ 3.31602997e-080,  2.16063140e+233,  8.48254144e+175,
         2.99688141e-080,  1.43769634e-023],
       [ 3.23225296e-295,  1.24571164e+137,  6.51686540e+256,
         9.98390183e+164,  3.89570063e+034],
       [ 7.38255668e+015,  6.46676985e+256,  5.03211681e-071,
         3.28175647e-028,  1.18338091e-202]])

### 3. Random

In [30]:
np.random.rand()

0.6168465356738736

In [31]:
np.random.randint(5)

3

In [32]:
np.seed = 1
np.random.randint(2,5)

2

In [33]:
np.random.rand(5,5)

array([[0.49199095, 0.17388953, 0.79175882, 0.57306814, 0.85261268],
       [0.44382322, 0.77602402, 0.4613258 , 0.30283692, 0.84614841],
       [0.37771497, 0.64352906, 0.01794344, 0.34356899, 0.65525675],
       [0.95772595, 0.60435052, 0.57823642, 0.1561396 , 0.78222535],
       [0.54715596, 0.1114633 , 0.83557974, 0.35630452, 0.00375059]])

In [34]:
np.round(np.random.rand(5,5))

array([[1., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 1.]])

In [35]:
# Ex 1. Please use random to generate this output
# ...

In [40]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([9, 3, 2, 2, 9])

In [50]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([3, 2, 1, 9, 8])

In [51]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.60421026, 0.83230245, 0.82351741, 0.06271456, 0.52177344],
       [0.07424902, 0.02550635, 0.88334454, 0.44616117, 0.77167211],
       [0.85703091, 0.07822169, 0.42077238, 0.5318623 , 0.23185833]])

In [78]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#

array([[0.04857608, 0.85002943, 0.35013482, 0.16819253, 0.        ],
       [0.69709023, 0.14991424, 0.58965247, 0.39854859, 0.        ],
       [0.69247406, 0.3861167 , 0.68374262, 0.27921749, 0.        ],
       [0.16405835, 0.28707906, 0.9137045 , 0.67939901, 0.        ],
       [0.29968674, 0.68488337, 0.26614799, 0.7615589 , 1.        ],
       [0.90652027, 0.6178217 , 0.16011215, 0.72110952, 1.        ],
       [0.20536233, 0.58104284, 0.65486566, 0.39189186, 1.        ],
       [0.16711598, 0.79725129, 0.33561273, 0.27937331, 0.        ],
       [0.96554438, 0.38083961, 0.96045915, 0.14326121, 1.        ],
       [0.77899213, 0.24589229, 0.81945906, 0.74423007, 1.        ]])

In [53]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 3,  7,  3,  6, 10],
       [ 0,  7,  7,  2,  1],
       [ 1,  4,  0,  9,  0],
       [ 0,  2,  7,  9,  8],
       [ 4, 10,  9,  4,  1]])

In [57]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 2, 1, 0, 1],
       [2, 1, 0, 0, 2],
       [2, 1, 0, 2, 0],
       [0, 2, 0, 0, 2],
       [2, 0, 1, 1, 1]])

In [60]:
i,j = np.where(np_matrix == 2)

In [61]:
i

array([0, 1, 1, 2, 2, 3, 3, 4])

In [62]:
j

array([1, 0, 4, 0, 3, 1, 4, 0])

In [67]:
#Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[idx,:]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [68]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[0, 2, 1, 0, 1],
       [0, 2, 0, 0, 2],
       [2, 0, 1, 1, 1]])

In [73]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[5, 6, 9, 6, 8],
       [2, 8, 1, 6, 0],
       [1, 0, 8, 4, 0],
       [1, 4, 1, 2, 2],
       [1, 7, 4, 5, 4]])

In [74]:
result = (np_matrix == 2)
result

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [False, False, False, False, False]])

In [75]:
np_matrix[result] = 99
np_matrix

array([[ 5,  6,  9,  6,  8],
       [99,  8,  1,  6,  0],
       [ 1,  0,  8,  4,  0],
       [ 1,  4,  1, 99, 99],
       [ 1,  7,  4,  5,  4]])

In [ ]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

data_matrix

In [80]:
#
#

array([[6, 2, 4, 9, 8],
       [0, 7, 0, 8, 1],
       [0, 7, 1, 4, 3],
       [7, 6, 8, 9, 6],
       [1, 6, 2, 6, 6],
       [2, 5, 9, 6, 4],
       [0, 2, 3, 6, 9],
       [4, 4, 0, 6, 5],
       [2, 2, 4, 7, 3],
       [3, 1, 0, 6, 8]])

label_vector

In [83]:
#
#

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 1])

train_data

In [84]:
#

array([[6, 2, 4, 9, 8],
       [0, 7, 0, 8, 1],
       [7, 6, 8, 9, 6],
       [2, 5, 9, 6, 4],
       [0, 2, 3, 6, 9],
       [2, 2, 4, 7, 3]])

test_data

In [85]:
#

array([[0, 7, 1, 4, 3],
       [1, 6, 2, 6, 6],
       [4, 4, 0, 6, 5],
       [3, 1, 0, 6, 8]])

In [90]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[5, 2, 5, 3, 3],
       [1, 3, 4, 2, 4],
       [3, 4, 3, 2, 1],
       [2, 4, 5, 3, 5],
       [5, 1, 5, 5, 4]])

### 4. Important Function

In [91]:
np.max(data)

5

In [92]:
np.max(data,0)

array([5, 4, 5, 5, 5])

In [93]:
np.max(data,1)

array([5, 4, 4, 5, 5])

In [95]:
np.sum(data)

84

In [96]:
np.average(data)

3.36

In [98]:
data[0,:]

array([5, 2, 5, 3, 3])

In [99]:
np.argmax(data[0,:])

0

In [100]:
np.argmin(data[0,:])

1

In [101]:
np.sort(data[0,:])

array([2, 3, 3, 5, 5])

In [105]:
np.argsort(data[0,:])

array([1, 3, 4, 0, 2])

In [106]:
#Ex.5 How to sort in decreasing order using np.sort
#

array([5, 5, 3, 3, 2])

In [108]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [109]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [127]:
data = np.round(np.random.random((5,5))*3)
data

array([[3., 1., 2., 2., 1.],
       [3., 1., 0., 1., 0.],
       [1., 1., 3., 1., 3.],
       [1., 1., 2., 2., 2.],
       [1., 2., 1., 1., 0.]])

In [128]:
data.shape

(5, 5)

In [129]:
data.reshape(1,25)

array([[3., 1., 2., 2., 1., 3., 1., 0., 1., 0., 1., 1., 3., 1., 3., 1.,
        1., 2., 2., 2., 1., 2., 1., 1., 0.]])

In [131]:
tile = [[1,2],
        [3,4]]
tile

[[1, 2], [3, 4]]

In [133]:
np.tile(tile,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [135]:
#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [139]:
#

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [141]:
# Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0]])